### ISSUE TITLE
 How to Access Weights：lssego_segmentation_48x32_b4x8_resnet_adam_24e_ponsplit_19.pth

### ISSUE THREAD

**Issue by EchoQiHeng** [fudan-zvg/RoadNet#2]
FileNotFoundError: ckpts/lssego_segmentation_48x32_b4x8_resnet_adam_24e_ponsplit_19.pth can not be found.

Thanks！！

**Comment by EchoQiHeng** [comment]
**How to define parameters related to the centerline?
       _Looking forward to your reply!_**
       
        self.types = copy.deepcopy(centerlines['type'])
        self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
        self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
        self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
        self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  
        self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
        self.centerlines = copy.deepcopy(centerlines['centerlines'])
        self.coeff = copy.deepcopy(centerlines)

**Comment by jefkine** [comment]
@EchoQiHeng, did you find a way to run this code? Even if assuming you train to obtain the weights, how do you approach this?

**Comment by EchoQiHeng** [comment]
> @EchoQiHeng, did you find a way to run this code? Even if assuming you train to obtain the weights, how do you approach this?

ResNetV1c -> mmdet.ResNet;

**Comment by EchoQiHeng** [comment]
> @EchoQiHeng, did you find a way to run this code? Even if assuming you train to obtain the weights, how do you approach this?

I am trying to use another backbone to replace it.

**Comment by JonnieWayy** [comment]
Same question with you. And when I tried to run the code with the two missed pkl files generated by myself. I still got the following error:
![image](https://github.com/fudan-zvg/RoadNet/assets/30260671/87ed0512-edef-4605-833b-56a89b102174)
The other attributes of the graph nodes are not given:
![image](https://github.com/fudan-zvg/RoadNet/assets/30260671/0b722240-44cb-4e84-b549-3551ac29392a)

**Comment by JonnieWayy** [comment]
> ```
>    **How to define parameters related to the centerline?
>    _Looking forward to your reply!_**
>    
>     self.types = copy.deepcopy(centerlines['type'])
>     self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
>     self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
>     self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
>     self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  
>     self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
>     self.centerlines = copy.deepcopy(centerlines['centerlines'])
>     self.coeff = copy.deepcopy(centerlines)
> ```

@EchoQiHeng Hi! Did you find a way to properly generate the 2 missed pkl files for defining these parameters?

**Comment by EchoQiHeng** [comment]
> > ```
> >    **How to define parameters related to the centerline?
> >    _Looking forward to your reply!_**
> >    
> >     self.types = copy.deepcopy(centerlines['type'])
> >     self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
> >     self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
> >     self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
> >     self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  
> >     self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
> >     self.centerlines = copy.deepcopy(centerlines['centerlines'])
> >     self.coeff = copy.deepcopy(centerlines)
> > ```
> 
> @EchoQiHeng Hi! Did you find a way to properly generate the 2 missed pkl files for defining these parameters?
Yes, you can try reloading the 'centerline' in custom_cuscenes_converter. py, and in my opinion, not all parameters are necessary.

**Comment by ZJWang9928** [comment]
> > > ```
> > >    **How to define parameters related to the centerline?
> > >    _Looking forward to your reply!_**
> > >    
> > >     self.types = copy.deepcopy(centerlines['type'])
> > >     self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
> > >     self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
> > >     self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
> > >     self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  
> > >     self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
> > >     self.centerlines = copy.deepcopy(centerlines['centerlines'])
> > >     self.coeff = copy.deepcopy(centerlines)
> > > ```
> > 
> > 
> > @EchoQiHeng Hi! Did you find a way to properly generate the 2 missed pkl files for defining these parameters?
> 
> Yes, you can try reloading the 'center_line' in custom_nuscenes_converter. py, and in my opinion, not all parameters are necessary.

Where is center_line' in custom_nuscenes_converter. py? I can't find this file in the repo...

**Comment by ZJWang9928** [comment]
> > > ```
> > >    **How to define parameters related to the centerline?
> > >    _Looking forward to your reply!_**
> > >    
> > >     self.types = copy.deepcopy(centerlines['type'])
> > >     self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
> > >     self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
> > >     self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
> > >     self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  
> > >     self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
> > >     self.centerlines = copy.deepcopy(centerlines['centerlines'])
> > >     self.coeff = copy.deepcopy(centerlines)
> > > ```
> > 
> > 
> > @EchoQiHeng Hi! Did you find a way to properly generate the 2 missed pkl files for defining these parameters?
> 
> Yes, you can try reloading the 'center_line' in custom_nuscenes_converter. py, and in my opinion, not all parameters are necessary.

Hi, how long does it take you to train the lanegraph2seq model for 300 epochs? In my experiment, each batch takes about 3.6 seconds, and hence the total training process will take about 20 days. Is this speed normal?

**Comment by YoushaaMurhij** [comment]
@EchoQiHeng, @ZJWang9928, Could you please guide me to add `center_lines` key to `custom_nuscenes_converter.py`?
I tried to prepare the data  using mmdetection3d v1.4.0:

```bash
python3 tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes_prycenterline_pon_split --version v1.0```

Is it the correct way?

**Comment by ZJWang9928** [comment]
> @EchoQiHeng, @ZJWang9928, Could you please guide me to add `center_lines` key to `custom_nuscenes_converter.py`? I tried to prepare the data using mmdetection3d v1.4.0:
> 
> ```shell
> python3 tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes_prycenterline_pon_split --version v1.0
> ```
> 
> Is it the correct way?

@YoushaaMurhij 
I modified tools/maptrv2/custom_nusc_map_converter.py from the repo of MapTRv2. It seems that only centerlines, start_point_idxs and end_point_idxs are needed. However, in RoadNetwork/rntr/core/centerline/structures/pryordered_bz_centerline.py: 
```
class NusClearOrederedBzCenterLine(object):
    def __init__(self, centerlines, grid_conf, bz_grid_conf, clear=True):
        self.types = copy.deepcopy(centerlines['type'])
        self.centerline_ids = copy.deepcopy(centerlines['centerline_ids'])
        self.incoming_ids = copy.deepcopy(centerlines['incoming_ids'])
        self.outgoing_ids = copy.deepcopy(centerlines['outgoing_ids'])
        self.start_point_idxs = copy.deepcopy(centerlines['start_point_idxs'])  # 问题出在这里 有三条中心线 start_idx==end_idx 所以和segmentation对不上
        self.end_point_idxs = copy.deepcopy(centerlines['end_point_idxs'])
        self.centerlines = copy.deepcopy(centerlines['centerlines'])
        self.coeff = copy.deepcopy(centerlines)
        # self.start_point_idxs = [0 for i in self.centerlines]
        # self.end_point_idxs = [len(centerline)-1 for centerline in self.centerlines]
```
The authors mention that for three of the centerlines start_idx==end_idx, which would cause some problem. And hence they fetch start_point_idxs and end_point_idxs from the pkl file instead of directly using the first and the last idx. Sadly, however, as the pkl files are not given, we barely know what they have done here.

**Comment by YoushaaMurhij** [comment]
@ZJWang9928, Thank you for your response and detailed asnwer!

**Comment by VictorLlu** [comment]
Sorry for the delay. I have updated the pretraining code. Please update the project and check out.
