### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by YoushaaMurhij** [fudan-zvg/RoadNet#4]
Thanks for sharing this great work!
Could you please provide the scripts/commads to prepare nuscenes data to match your dataloader?
I tried mmdetection3d v1.4.0 but the info keys do not match with the ones used to train this model.
And it is not clear how to get `center_lines` info.

Thanks!

**Comment by VictorLlu** [comment]
Sorry for the delay. I have updated the data pretraining guideline in get_started. Please update the project and check out.

**Comment by ZJWang9928** [comment]
> Sorry for the delay. I have updated the data pretraining guideline in get_started. Please update the project and check out.

@VictorLlu Hello! Could you please update the missing `nuscenes_converter_pon_centerline` file recently? It would be of great help! Thank you.
