### ISSUE TITLE
Inference code for lanegraph2seq seems wrong

### ISSUE THREAD

**Issue by ZJWang9928** [fudan-zvg/RoadNet#6]
Hi! I found that the test/inference code in RoadNetwork/rntr/ar_lanegraph2seq.py is the same with the test/inference code in RoadNetwork/rntr/ar_rntr.py, which is for RNTR instead of Lanegraph2Seq.
Would you please update the test/inference code for Lanegraph2Seq? Thank you so much!

**Comment by VictorLlu** [comment]
I'm currently addressing the dataloader timing issue. If necessary, I can prioritize adding the inference code within the next few days.

**Comment by ZJWang9928** [comment]
@VictorLlu
Thank you for your update and reply.
Can you please also add the code for performance evaluation recently?
BTW, when running the training code, I print time for data preprocessing (time1), forward propagation (time2) and back propagation (time3) in mmengine/model/wrappers/distributed.py when training with 8 GPUs. It seems that the major cause for the long average batch time is **the extremely slow back propagation in some iterations**.
![image](https://github.com/fudan-zvg/RoadNet/assets/30260671/bc803240-821c-45ae-91af-15dca4ebcb41)
You can refer to #3 for details. I hope this can to some extent help you.

**Comment by xiaolul2** [comment]
@ZJWang9928 @VictorLlu Hello, I am a little confused. There is no train.py and dist_train.sh files. How to run the code....

**Comment by VictorLlu** [comment]
Thank you for your contribution. I've implemented the inference code for AR-RNTR first. You can utilize test.py, or it will automatically perform an evaluation after every 50 epochs.
